### ISSUE TITLE
AttributeError: 'FileDataset' object has no attribute 'RegistrationSequence'

### ISSUE THREAD

**Issue by tanjia123456** [brianmanderson/RegisteringImages#2]
Hello, thanks for your contribution!

I feel confused about how to register  dicom， i have no template
`
from RegisterImages.WithDicomReg import register_images_with_dicom_reg, pydicom, sitk
from DicomRTTool import DicomReaderWriter
import pydicom

registration_file = "CTA-GAN/PA2/SE1/IM66.IMA"
dicom_registration = pydicom.read_file(registration_file)

fixed_image = sitk.ReadImage("CTA-GAN/PA2/SE1/IM66.IMA",sitk.sitkInt32)
moving_image = sitk.ReadImage("CTA-GAN/PA1/SE1/IM66.IMA",sitk.sitkInt32)

resampled_moving = register_images_with_dicom_reg(fixed_image=fixed_image, moving_image=moving_image, dicom_registration=dicom_registration)
# AttributeError: 'FileDataset' object has no attribute 'RegistrationSequence'---> dicom_registration as no attribute 'RegistrationSequence
`

I have two MRI dicom file, the moving_path is the dicom file that needs to be registered， so what is dicom_registration ?

**Comment by brianmanderson** [comment]
*edit to add commit
Hi tanjia,

I'm sorry the program is causing you issues. I'm not very familiar with how a .IMA file is set up, but assuming it has the same attributes as a DICOM registration file, it ought to look something like this: https://dicom.innolitics.com/ciods/spatial-registration/spatial-registration/00700308

Could you please provide a print statement of
```
registration_file = "CTA-GAN/PA2/SE1/IM66.IMA"
dicom_registration = pydicom.read_file(registration_file)
print(dicom_registration.__dict__)
```
Just to see what tags are available?

As an aside, if you can find the 16 length rigid matrix that you are wanting to use, you can do what are you currently presenting. I've made a new commit to take either a DICOM registration file or an array of 16 numbers.

Commit 6803d3a
 
Hope that helps!
Brian

**Comment by brianmanderson** [comment]
*Also did not mean to close this without your thumbs up

**Comment by tanjia123456** [comment]
> *edit to add commit Hi tanjia,
> 
> I'm sorry the program is causing you issues. I'm not very familiar with how a .IMA file is set up, but assuming it has the same attributes as a DICOM registration file, it ought to look something like this: https://dicom.innolitics.com/ciods/spatial-registration/spatial-registration/00700308
> 
> Could you please provide a print statement of
> 
> ```
> registration_file = "CTA-GAN/PA2/SE1/IM66.IMA"
> dicom_registration = pydicom.read_file(registration_file)
> print(dicom_registration.__dict__)
> ```
> 
> Just to see what tags are available?
> 
> As an aside, if you can find the 16 length rigid matrix that you are wanting to use, you can do what are you currently presenting. I've made a new commit to take either a DICOM registration file or an array of 16 numbers.
> 
> Commit [6803d3a](https://github.com/brianmanderson/RegisteringImages/commit/6803d3ae208e88908b88ac853f8abda87d8af7e1)
> 
> Hope that helps! Brian

Yes, the .IMA is the original image, it's dicom file, print info show as following:

**Comment by tanjia123456** [comment]
> > *edit to add commit Hi tanjia,
> > I'm sorry the program is causing you issues. I'm not very familiar with how a .IMA file is set up, but assuming it has the same attributes as a DICOM registration file, it ought to look something like this: https://dicom.innolitics.com/ciods/spatial-registration/spatial-registration/00700308
> > Could you please provide a print statement of
> > ```
> > registration_file = "CTA-GAN/PA2/SE1/IM66.IMA"
> > dicom_registration = pydicom.read_file(registration_file)
> > print(dicom_registration.__dict__)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Just to see what tags are available?
> > As an aside, if you can find the 16 length rigid matrix that you are wanting to use, you can do what are you currently presenting. I've made a new commit to take either a DICOM registration file or an array of 16 numbers.
> > Commit [6803d3a](https://github.com/brianmanderson/RegisteringImages/commit/6803d3ae208e88908b88ac853f8abda87d8af7e1)
> > Hope that helps! Brian
> 
> Yes, the .IMA is the original image, it's dicom file, print info show as following:

![Uploading 捕获.PNG…]()

**Comment by brianmanderson** [comment]
Doesn't look like the .png file is coming over unfortunately

**Comment by tanjia123456** [comment]
> Doesn't look like the .png file is coming over unfortunately

There's a lot of printed information, I can only paste part of it

{'_parent_encoding': 'iso8859', '_dict': {(0008, 0005): (0008, 0005) Specific Character Set              CS: 'ISO_IR 100', (0008, 0008): RawDataElement(tag=(0008, 0008), VR='CS', length=30, value=b'ORIGINAL\\PRIMARY\\M\\DIS2D\\NORM ', value_tell=346, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0012): RawDataElement(tag=(0008, 0012), VR='DA', length=8, value=b'20230614', value_tell=384, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0013): RawDataElement(tag=(0008, 0013), VR='TM', length=14, value=b'190012.692000 ', value_tell=400, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0016): RawDataElement(tag=(0008, 0016), VR='UI', length=26, value=b'1.2.840.10008.5.1.4.1.1.4\x00', value_tell=422, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0018): RawDataElement(tag=(0008, 0018), VR='UI', length=50, value=b'1.3.12.2.1107.5.2.0.79131.202306141900122801309803', value_tell=456, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0020): RawDataElement(tag=(0008, 0020), VR='DA', length=8, value=b'20230614', value_tell=514, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0021): RawDataElement(tag=(0008, 0021), VR='DA', length=8, value=b'20230614', value_tell=530, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0022): RawDataElement(tag=(0008, 0022), VR='DA', length=8, value=b'20230614', value_tell=546, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0023): RawDataElement(tag=(0008, 0023), VR='DA', length=8, value=b'20230614', value_tell=562, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0030): RawDataElement(tag=(0008, 0030), VR='TM', length=14, value=b'172539.187000 ', value_tell=578, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0031): RawDataElement(tag=(0008, 0031), VR='TM', length=14, value=b'190012.597000 ', value_tell=600, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0032): RawDataElement(tag=(0008, 0032), VR='TM', length=14, value=b'184901.685000 ', value_tell=622, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0033): RawDataElement(tag=(0008, 0033), VR='TM', length=14, value=b'190012.692000 ', value_tell=644, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0050): RawDataElement(tag=(0008, 0050), VR='SH', length=0, value=b'', value_tell=666, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0060): RawDataElement(tag=(0008, 0060), VR='CS', length=2, value=b'MR', value_tell=674, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0070): RawDataElement(tag=(0008, 0070), VR='LO', length=8, value=b'SIEMENS ', value_tell=684, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0080): RawDataElement(tag=(0008, 0080), VR='LO', length=28, value=b'Chongqing Southwest Hospital', value_tell=700, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0081): RawDataElement(tag=(0008, 0081), VR='ST', length=58, value=b'Street StreetNo,Congqing City/4S84F-VRYYT/,District,CN,ZIP', value_tell=736, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0090): RawDataElement(tag=(0008, 0090), VR='PN', length=0, value=b'', value_tell=802, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 1010): RawDataElement(tag=(0008, 1010), VR='SH', length=8, value=b'AWP79131', value_tell=810, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 1030): RawDataElement(tag=(0008, 1030), VR='LO', length=8, value=b'CJF^CSVD', value_tell=826, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 103e): RawDataElement(tag=(0008, 103e), VR='LO', length=18, value=b't1_spc_tra_VWALL+C', value_tell=842, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 1040): RawDataElement(tag=(0008, 1040), VR='LO', length=10, value=b'Department', value_tell=868, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 1050): RawDataElement(tag=(0008, 1050), VR='PN', length=0, value=b'', value_tell=886, is_implicit_VR=False, is_little_endian=True, is_raw=True)

\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'file_meta': (0002, 0000) File Meta Information Group Length  UL: 176
(0002, 0001) File Meta Information Version       OB: b'\x00\x01'
(0002, 0002) Media Storage SOP Class UID         UI: MR Image Storage
(0002, 0003) Media Storage SOP Instance UID      UI: 1.3.12.2.1107.5.2.0.79131.202306141900122801309803
(0002, 0010) Transfer Syntax UID                 UI: Explicit VR Little Endian
(0002, 0012) Implementation Class UID            UI: 1.3.12.2.1107.5.2
(0002, 0013) Implementation Version Name         SH: 'MR_VE12U', 'fileobj_type': <built-in function open>, 'filename': 'CTA-GAN/PA2/SE1/IM66.IMA', 'timestamp': 1686787481.523183}

**Comment by tanjia123456** [comment]
> Doesn't look like the .png file is coming over unfortunately

There's a lot of printed information, I can only paste part of it

{'_parent_encoding': 'iso8859', '_dict': {(0008, 0005): (0008, 0005) Specific Character Set              CS: 'ISO_IR 100', (0008, 0008): RawDataElement(tag=(0008, 0008), VR='CS', length=30, value=b'ORIGINAL\\PRIMARY\\M\\DIS2D\\NORM ', value_tell=346, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0012): RawDataElement(tag=(0008, 0012), VR='DA', length=8, value=b'20230614', value_tell=384, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0013): RawDataElement(tag=(0008, 0013), VR='TM', length=14, value=b'190012.692000 ', value_tell=400, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0016): RawDataElement(tag=(0008, 0016), VR='UI', length=26, value=b'1.2.840.10008.5.1.4.1.1.4\x00', value_tell=422, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0018): RawDataElement(tag=(0008, 0018), VR='UI', length=50, value=b'1.3.12.2.1107.5.2.0.79131.202306141900122801309803', value_tell=456, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0020): RawDataElement(tag=(0008, 0020), VR='DA', length=8, value=b'20230614', value_tell=514, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0021): RawDataElement(tag=(0008, 0021), VR='DA', length=8, value=b'20230614', value_tell=530, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0022): RawDataElement(tag=(0008, 0022), VR='DA', length=8, value=b'20230614', value_tell=546, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0023): RawDataElement(tag=(0008, 0023), VR='DA', length=8, value=b'20230614', value_tell=562, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0030): RawDataElement(tag=(0008, 0030), VR='TM', length=14, value=b'172539.187000 ', value_tell=578, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0031): RawDataElement(tag=(0008, 0031), VR='TM', length=14, value=b'190012.597000 ', value_tell=600, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0032): RawDataElement(tag=(0008, 0032), VR='TM', length=14, value=b'184901.685000 ', value_tell=622, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0033): RawDataElement(tag=(0008, 0033), VR='TM', length=14, value=b'190012.692000 ', value_tell=644, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0050): RawDataElement(tag=(0008, 0050), VR='SH', length=0, value=b'', value_tell=666, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0060): RawDataElement(tag=(0008, 0060), VR='CS', length=2, value=b'MR', value_tell=674, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0070): RawDataElement(tag=(0008, 0070), VR='LO', length=8, value=b'SIEMENS ', value_tell=684, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0080): RawDataElement(tag=(0008, 0080), VR='LO', length=28, value=b'Chongqing Southwest Hospital', value_tell=700, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0081): RawDataElement(tag=(0008, 0081), VR='ST', length=58, value=b'Street StreetNo,Congqing City/4S84F-VRYYT/,District,CN,ZIP', value_tell=736, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 0090): RawDataElement(tag=(0008, 0090), VR='PN', length=0, value=b'', value_tell=802, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 1010): RawDataElement(tag=(0008, 1010), VR='SH', length=8, value=b'AWP79131', value_tell=810, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 1030): RawDataElement(tag=(0008, 1030), VR='LO', length=8, value=b'CJF^CSVD', value_tell=826, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 103e): RawDataElement(tag=(0008, 103e), VR='LO', length=18, value=b't1_spc_tra_VWALL+C', value_tell=842, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 1040): RawDataElement(tag=(0008, 1040), VR='LO', length=10, value=b'Department', value_tell=868, is_implicit_VR=False, is_little_endian=True, is_raw=True), (0008, 1050): RawDataElement(tag=(0008, 1050), VR='PN', length=0, value=b'', value_tell=886, is_implicit_VR=False, is_little_endian=True, is_raw=True)

\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'file_meta': (0002, 0000) File Meta Information Group Length  UL: 176
(0002, 0001) File Meta Information Version       OB: b'\x00\x01'
(0002, 0002) Media Storage SOP Class UID         UI: MR Image Storage
(0002, 0003) Media Storage SOP Instance UID      UI: 1.3.12.2.1107.5.2.0.79131.202306141900122801309803
(0002, 0010) Transfer Syntax UID                 UI: Explicit VR Little Endian
(0002, 0012) Implementation Class UID            UI: 1.3.12.2.1107.5.2
(0002, 0013) Implementation Version Name         SH: 'MR_VE12U', 'fileobj_type': <built-in function open>, 'filename': 'CTA-GAN/PA2/SE1/IM66.IMA', 'timestamp': 1686787481.523183}

**Comment by brianmanderson** [comment]
In that case, I'd recommend looking through the information available, and see if you can find the RegistrationMatrix. If you're unable to find it, we could hop on a quick Zoom call.

**Comment by brianmanderson** [comment]
Reaching out again as a follow-up on this

**Comment by brianmanderson** [comment]
closing since I've not heard anything
