### ISSUE TITLE
Can't use registerDicom to register two full MRIs

### ISSUE THREAD

**Issue by Alejo031** [brianmanderson/RegisteringImages#4]
I edited the original issue, since I ended up finding that it was a matter of me not supplying a 3D matrix, but rather a list of images. 
After that I was able to successfully run "registerDicom" without getting any error messages, but still haven't been able to get a propper registered image. Right now I call registerDicom while providing two SimpleITK elements with the 3d stack of images of my fixed and moving MRIs, the Series Instance UID of my moving image as a string, and an element with my registration file, the other fields were left blank. 
The current issue is that when I try to visualize the registered MRI I get a distorted black square. I tried testing the visualization function with the original images and it seems works fine with the fixed and moving images.
I've been trying to change the way i visualize the image in case the problem was the way I was splitting the 3d stack back into slices, but still failed to fix it. 
In case you need the info, my code creates a list of dicom elements using pydicom's dcmread, splits the data between a dict with the metadata and a SimpleITK list with the pixel matrix of each slice and then combines all those slices into a 3D element I can load into registerDicom. After I run registerDicom I try to visualize the new images either as the 3d version or the individual slices but get the same result. 
Let me know if you have any ideas of what the problem might be or if you need me to provide any more information

![problem](https://github.com/brianmanderson/RegisteringImages/assets/172634423/ec843cab-c3b6-44f7-9822-36f7cbd7cbe4)

Image on the left is the sitk list of the fixed image and the one on the right is the sitk list obtained after I split the 3D sitk element. In case it's relevant, when i check the value of the pixel my mouse stopped into, it shows values similar to the ones on the original moving image on the same place, so it seems the data is not lost

**Comment by Alejo031** [comment]
After some trial and error I found out that the issue was related to the way I was loading my dicom data (probably a rookie mistake, but worth saying it in case it's useful to someone else). If anyone runs into a similar problem while trying to register multiple images, I solved it using SimpleITK's ImageSeriesReader method to get my image data, instead of using pydicom and then splitting images and metadata apart.

**Comment by brianmanderson** [comment]
Hi Alejo,

I'm sorry for not responding back sooner, but am glad that everything is resolved.

To create images, I'd suggest (rather selfishly so) that you look at this tool: https://github.com/brianmanderson/Dicom_RT_and_Images_to_Mask

It leverages SimpleITK's image series reader to make Sitk handles

Thanks!
Brian

**Comment by Alejo031** [comment]
Hi Brian,

Don't worry about it. Since I don't have much programming experience, solving the problem turned out to be an excellent way to get into the subject and understand how registerDicom works. I will also look at the tool you mentioned; I am sure it will help me improve my code and make it more robust.

On another subject, my next objective for my code is to turn the registered and processed images back into DICOM files. I would really appreciate any suggestions you could give me on how to create proper DICOM metadata, as I need to export the images back into medical-grade software and I'm sure it will reject any files that lack proper metadata (I tried importing files created with 3D Slicer for another task, and they were rejected due to unspecified formatting requirements).

Thank you for any insights you provide and for the code you've already developed, It has been very useful in the development of my project, and I'll be sure to mention it when I present my results.

Best regards,

Alejo

Edit: I realized I was not very clear on the kind of metadata I need to create. I thought about copying patient-related metadata from the original DICOM files, but I'm worried about study-specific metadata, such as the Series Instance UID used when I use registerDicom.

**Comment by brianmanderson** [comment]
I'm glad it could be a useful learning experience!

For changing meta-data and writing out DICOM files, SimpleITK is going to be your best bet. This link shows a nice example in python: https://simpleitk.readthedocs.io/en/v1.2.2/Examples/DicomSeriesReadModifyWrite/Documentation.html

The list of 'tags to copy' shows a bunch of dicom elements ( (0010|0010) for Patient Name, for example)

If you want to know where the values come from, I'd recommend looking at this: https://dicom.innolitics.com/ciods/mr-image The website has a nice description of the DICOM data elements and their respective keys.

Brian

**Comment by Alejo031** [comment]
Thanks Brian! I'll be sure to look that up
